name: Build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.run }}
    strategy:
      matrix:
        include:
          - { run: ubuntu-latest,  os: linux,   arch: amd64 }
          - { run: ubuntu-latest,  os: linux,   arch: arm64 }
          - { run: macos-latest,   os: darwin,  arch: amd64 }
          - { run: macos-latest,   os: darwin,  arch: arm64 }
          - { run: windows-latest, os: windows, arch: amd64 }
          - { run: windows-latest, os: windows, arch: arm64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: make build
        env:
          GOOS: ${{ matrix.os }}
          GOACH: ${{ matrix.arch }}
